//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMSOSPS.Cloud.Data.CloudContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Approve
    {
        public int F_ID { get; set; }
        public string F_OrderNo { get; set; }
        public string F_WMSCode { get; set; }
        public string F_EnterpriseCode { get; set; }
        public string F_UserID { get; set; }
        public Nullable<float> F_TruckWeight { get; set; }
        public Nullable<float> F_GrossWeight { get; set; }
        public Nullable<float> F_NetWeight { get; set; }
        public Nullable<float> F_BillWeight { get; set; }
        public Nullable<System.DateTime> F_DateTime { get; set; }
    }
}
