//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMSOSPS.Cloud.Data.CloudContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Enterprise
    {
        public string F_Code { get; set; }
        public string F_WMSPrefix { get; set; }
        public string F_Name { get; set; }
        public string F_WSURL { get; set; }
        public string F_WSUserID { get; set; }
        public string F_WMPassword { get; set; }
    }
}
