//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMSOSPS.Cloud.Data.CloudContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SAPOIL
    {
        public int F_ID { get; set; }
        public string F_OILName { get; set; }
        public string F_INVOICE { get; set; }
        public string F_TYPE { get; set; }
        public string F_OILCODE { get; set; }
        public string F_Location { get; set; }
        public string F_DESCRIPTION { get; set; }
        public Nullable<int> F_IsRealName { get; set; }
    }
}
