//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMSOSPS.Cloud.Data.CloudContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_User
    {
        public string F_UserID { get; set; }
        public string F_Name { get; set; }
        public string F_Password { get; set; }
        public Nullable<int> F_GroupID { get; set; }
        public string F_BelongTo { get; set; }
        public Nullable<bool> F_Enable { get; set; }
        public string F_Description { get; set; }
    }
}
