//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMSOSPS.Cloud.Data.CloudContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_WMSSrvUploadStatus
    {
        public int F_ID { get; set; }
        public string LIPS_VBELN { get; set; }
        public Nullable<int> LIPS_COMMAND { get; set; }
        public Nullable<int> LIPS_POSNR { get; set; }
        public Nullable<int> LIPS_ZLOCATION { get; set; }
        public Nullable<int> LIPS_CARDNO { get; set; }
        public Nullable<decimal> LIPS_ZVLFIMG_01 { get; set; }
        public Nullable<System.DateTime> LIPS_ZVDATE_01 { get; set; }
        public Nullable<System.DateTime> LIPS_ZVTIME_01 { get; set; }
        public string LIPS_ZVUNAME_01 { get; set; }
        public Nullable<decimal> LIPS_ZVLFIMG_02 { get; set; }
        public Nullable<System.DateTime> LIPS_ZVDATE_02 { get; set; }
        public Nullable<System.DateTime> LIPS_ZVTIME_02 { get; set; }
        public string LIPS_ZVUNAME_02 { get; set; }
        public Nullable<decimal> LIPS_ZVLFIMG_NET { get; set; }
        public Nullable<decimal> LIPS_PKQUAN { get; set; }
        public Nullable<decimal> LIPS_PKTARE { get; set; }
        public string LIPS_NOTES { get; set; }
        public string ZMESSAGE { get; set; }
        public string REMARK1 { get; set; }
        public string REMARK2 { get; set; }
        public string REMARK3 { get; set; }
        public string REMARK4 { get; set; }
        public string REMARK5 { get; set; }
        public string REMARK6 { get; set; }
        public Nullable<float> F_OILDefine { get; set; }
        public string F_TruckNo { get; set; }
        public string F_RecvCompany { get; set; }
        public string F_CompanyCode { get; set; }
        public string F_OILName { get; set; }
        public string F_OILCode { get; set; }
        public string F_DriverIDNo { get; set; }
        public string F_DriverName { get; set; }
        public string F_WMSCode { get; set; }
        public Nullable<int> IsExist { get; set; }
        public string LOAD_TYPE { get; set; }
        public Nullable<int> F_BillStatus { get; set; }
        public System.DateTime F_DateTime { get; set; }
        public Nullable<int> F_UploadEB { get; set; }
        public Nullable<System.DateTime> F_UploadTime { get; set; }
        public Nullable<int> F_UploadTimes { get; set; }
        public Nullable<int> F_Download { get; set; }
        public Nullable<System.DateTime> F_DownloadTime { get; set; }
        public Nullable<int> F_DownloadTimes { get; set; }
    }
}
